version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=batmon.settings
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A batmon worker -l info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=batmon.settings
    depends_on:
      - db
      - redis
      - web

  celery_beat:
    build: .
    command: celery -A batmon beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=batmon.settings
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data: