# Generated by Django 5.0.10 on 2025-10-01 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url_or_host', models.CharField(max_length=255)),
                ('check_type', models.CharField(choices=[('ping', 'Ping (ICMP)'), ('http', 'HTTP/HTTPS'), ('tcp', 'TCP Port')], max_length=10)),
                ('interval', models.IntegerField(default=60, help_text='Intervalo de execução em segundos')),
                ('timeout', models.IntegerField(default=10, help_text='Timeout em segundos')),
                ('status_atual', models.CharField(choices=[('ok', 'OK'), ('fail', 'Falha'), ('alert', 'Em Alerta'), ('maintenance', 'Em Manutenção')], default='ok', max_length=15)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('periodic_task', models.ForeignKey(blank=True, help_text='Celery Periodic Task associated with this check.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
            ],
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('response_time', models.FloatField(blank=True, help_text='Tempo de resposta em segundos', null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitoring.servicecheck')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
