# Generated by Django 5.0.10 on 2025-10-01 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('webhook', 'Webhook'), ('command', 'Command')], max_length=10)),
                ('trigger', models.CharField(choices=[('on_fail', 'When service fails'), ('on_recovery', 'When service recovers'), ('on_fail_x_times', 'When service fails X times in a row')], default='on_fail', max_length=20)),
                ('trigger_value', models.IntegerField(blank=True, help_text="Number of failures for 'on_fail_x_times' trigger", null=True)),
                ('config', models.JSONField(default=dict, help_text='JSON configuration for the alert (e.g., email address, bot token, chat ID, webhook URL, command)')),
                ('active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.servicecheck')),
            ],
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_sent', models.TextField()),
                ('success', models.BooleanField(default=False)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitoring.alert')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
